[build]
builder          = "DOCKERFILE"
dockerfilePath   = "Dockerfile"
buildContext     = "."

[deploy]
healthcheckPath    = "/api/health"
healthcheckTimeout = 30
restartPolicyType  = "ON_FAILURE"
numReplicas        = 1
